baseurl = "/"
languageCode = "en-us"
title = "Gerry Tonkin-Hill"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 3
[[menu.main]]
    name = "Software"
    url = "/software/"
    weight = 4
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 5

[params]
      description = "Gerry Tonkin-Hill's personal website."
      footer = "[Github](https://github.com/gtonkinhill) | [Twitter](https://twitter.com/gerrythill) | [ORCID](https://orcid.org/0000-0003-4397-2224)"
      favicon = "favicon.png"
